# Generated by Django 3.2 on 2023-01-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230120_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsss',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pic/blogimage/'),
        ),
    ]
