# Generated by Django 3.2 on 2023-01-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_formsss_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsss',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/blogimage/'),
        ),
    ]
