# Generated by Django 3.2 on 2023-01-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
