# Generated by Django 3.2 on 2023-01-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_book_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='start_time',
            field=models.DateField(),
        ),
    ]
